### ISSUE TITLE
Resolution of the program version 2.4.1

### ISSUE THREAD

**Issue by juanbosh** [flathub/linux-store-backend#13]
The resolucion of the program is low and the icons are pixalated, i install the driver for nvidia card in ubuntu 18.04 and continues the same. I download the version 2.4.3 app and works properly. How i can fixed the resolution of the program. No video, no other thing the resolution of the program in the screen. 

thanks

**Comment by jgarciao** [comment]
This issue tracker is for bugs and features of the flathub.org website backend. 

If you have any issue with an app distributed in flathub.org go to the app description page and click on the "Issues" button. If that button is not there, go to the website of the app and try to find a issue tracker or community forum

Here is [an example](https://flathub.org/apps/details/org.octave.Octave) for another app

Note: you forgot to mention the name of the application you are having problems with
