### ISSUE TITLE
Title field in .flatpakref files uses ID instead of friendly name

### ISSUE THREAD

**Issue by davidmhewitt** [flathub/linux-store-backend#22]
As far as I can tell from the code, the .flatpakref files generated by the backend should have something like:

`Title=Geary from flathub` where the "Geary" part of the string is pulled from the `<name>` tag of the AppData file.

What actually seems to be happening is that we end up with the ID of the application there, so we end up with things like:
`Title=org.gnome.Geary from flathub`

I've tried with a selection of different .flatpakref files downloaded from flathub and this seems to be consistent across all of the ones I've downloaded. But as far as I can tell, the code makes sense and should be working, so I'm not sure where it's going wrong.

**Comment by davidmhewitt** [comment]
After a bit more digging, I've found that these flatpakref files are generated by `flat-manager` and have nothing to do with this repo. However, I'll leave this issue open for now in case there's anything that can be done here.

**Comment by barthalion** [comment]
I don't think so. As you said, it's handled by flat-manager.
