### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by takluyver** [flathub/linux-store-backend#6]
Apologies if I've missed it, but it doesn't look like the REST API is documented anywhere. Looking at the code, I was able to figure out:

- `/api/v1/apps` (list all apps)
- `/api/v1/apps/category/Game`
  - List of available categories?
- `/api/v1/apps/collection/recently-updated`
- `/api/v1/apps/com.play0ad.zeroad` (more info on a single application)

**Comment by jgarciao** [comment]
You are right. The API is not documented yet. One of the reasons is because is not stable yet. I will add a warning about that

**Comment by ohaessler** [comment]
Is there any documentation now for the API and is it stable?

**Comment by jgarciao** [comment]
Flathub.org's backend was replaced recently by [this one](https://github.com/flathub/backend/)

I'm closing this issue as this repo is going to be archived soon.
